### ISSUE TITLE
已经不需要 fastclick 了

### ISSUE THREAD

**Issue by justorez** [evestorm/front-end-interview#3]
Notion 文章：https://willbchang.notion.site/dda2beec1b0d44ca8b2f8e923778c70c
为什么不再需要 fastclick：https://juejin.cn/post/6844904168092614670

**Comment by evestorm** [comment]
感谢指正，已[更新文章](https://willbchang.notion.site/dda2beec1b0d44ca8b2f8e923778c70c#8404d332f9554cd2a66be3f7db9d65f2) @justorez
